### ISSUE TITLE
Using VSTest 2017 with Fakes, no results to commit

### ISSUE THREAD

**Issue by CallumDawHexagon** [OpenCover/opencover#831] opened 2018-08-01 13:26 UTC
### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [X ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [X] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Get code coverage results from an OpenCover test run when using Fakes assemblies

### Actual Behavior

When running VS2017 test agent and using Fakes, get:
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.

Removing the Fakes from the directory returns coverage as expected.

Using VS2015 Update 3 with or without Fakes returns coverage as expected

### Steps to reproduce the problem:

Run OpenCover with DLLs that use Fakes using the VS2017 vstest.console.exe.

**Comment by Birgos** [comment] 2018-08-10 14:54
I don't know if my answer also addresses this issue, but we had the following problems:

### Framework
 \>= .NET 4.5

### Environment
Windows Server 2012 R2
TeamCity 8.1.1
OpenCover OpenCover.4.6.519

### Problem
NUnits tests are running - but no coverage being recorded under teamcity

?! Running local on my own pc - coverage was being recorded....

### I had already (studying the problem since 2 weeks now)...
  repeated the problem using the latest stable release of OpenCover.
  reviewed the usage guide and usage document.
  have looked at the opencover output xml file in an attempt to resolve the issue.
  reviewed the current issues to check that the issue isn't already known.
  cloned the repository and created a new version with a lot of debugging messages
  ...many more - too much to explain it here ;-)

I had a hunch that the opencover profiler (c++ project) could not longer correctly register himself, but the debugging messages showed me that the profiler could register himself successfully :-(

### Reason
I found out, that OpenCover stopped working on our build agents, after installing the Windows July-2018 security rollup.

### Solution
Today I found this MSDN Article: ["Access Denied" errors and applications with COM activation fail after installing July 2018 Security and Quality Rollup updates for .NET Framework](https://support.microsoft.com/am-et/help/4345913/access-denied-errors-after-installing-july-2018-security-rollup-update)

This article refers to **various fixes** for resolving the issues encountered when installing the **KB4345913** update. The update i was interested in: [KB4346406](https://support.microsoft.com/am-et/help/4346406/update-for-net-framework-4-6-4-6-1-4-6-2-4-7-4-7-1-and-4-7-2-on-window)

After the installation of the update **KB4346406** OpenCover ran **as usual and was able to calculate the coverage again!**

**Comment by onuralp** [comment] 2018-08-13 13:16
@Birgos thank you for sharing your experience. 

After reading your comment, I gave it a try however it didn't work for me.
I've installed that Windows update to my Windows 2016 Server build server. Nothing changed. 

I created a Windows 2012 R2 from scratch, installed VS17 Enterprise and KB4346406. Nothing changed as well.

Still having `No results, this could be for a number of reasons..` Do I miss something?

**Comment by onuralp** [comment] 2018-08-14 08:08
Hi, After I spent a week (I tried almost all combination of MSBuild, VS, dotCover, OpenCover with any version) I found the way. VsTest generates code coverage files.

I created a gist. I hope it helps someone https://gist.github.com/onuralp/a659641f0eac24c4e732422e0d0e80ce

**Closed** 2019-01-01 03:47 UTC
