### ISSUE TITLE
Exception in RunProcess for OpenCover.Console

### ISSUE THREAD

**Issue by diogonborges** [OpenCover/opencover#647] opened 2016-11-30 18:28 UTC
Please provide the following information when submitting an issue, where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [X] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [X] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

OpenCover report

### Actual Behavior
Stack trace follows
 Executing: C:\build-dir\ISS-UMS-JOB1\user-management-service\packages\xunit.runner.console.2.1.0\tools\xunit.console.exe
30-Nov-2016 18:20:23 	  At: CurrentDomainOnUnhandledException
30-Nov-2016 18:20:23 	  An System.ArgumentException occured: Item has already been added. Key in dictionary: 'PATH'  Key being added: 'Path'
30-Nov-2016 18:20:23 	  stack:    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
30-Nov-2016 18:20:23 	     at System.Diagnostics.ProcessStartInfo.get_EnvironmentVariables()
30-Nov-2016 18:20:23 	     at OpenCover.Console.Program.RunProcess(CommandLineParser parser, Action`1 environment) in c:\projects\opencover\main\OpenCover.Console\Program.cs:line 361
30-Nov-2016 18:20:23 	     at OpenCover.Console.Program.<>c__DisplayClass6.<RunWithContainer>b__3(Action`1 environment) in c:\projects\opencover\main\OpenCover.Console\Program.cs:line 169
30-Nov-2016 18:20:23 	     at OpenCover.Framework.Manager.ProfilerManager.<>c__DisplayClass3.<SetProfilerAttributes>b__1(Object state) in c:\projects\opencover\main\OpenCover.Framework\Manager\ProfilerManager.cs:line 132
30-Nov-2016 18:20:23 	     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
30-Nov-2016 18:20:23 	     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
30-Nov-2016 18:20:23 	     at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
30-Nov-2016 18:20:23 	     at System.Threading.ThreadPoolWorkQueue.Dispatch()
30-Nov-2016 18:20:23 	  A report has been sent to the OpenCover development team...

### Steps to reproduce the problem:

Tried running OpenCover, latest release, from nuget, in Bamboo.

Example command line:
C:\build-dir\ISS-UMS-JOB1\user-management-service\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:C:\build-dir\ISS-UMS-JOB1\user-management-service\packages\xunit.runner.console.2.1.0\tools\xunit.console.exe -targetargs:"<a couple of dlls...  .\abc.dll \.bca.dll \.xyz.dll> -noshadow -nunit test-reports\report.nunit.xml" -register:Path64 -hideskipped:All -excludebyattribute:System.ObsoleteAttribute -filter:"+[*]*-[*xunit*]*" -output:test-reports\OpenCover-results.xml

**Comment by sawilde** [comment] 2017-04-15 23:20
@diogonborges I can't determine the cause of this error as OpenCover does not insert the Path variable into the environment variables.

If you have a repeatable scenario then please reopen (p.s. I don't use bamboo - so if it only happens on that environment then I can't help without access to that environment)

**Comment by sawilde** [comment] 2017-04-15 23:57
A similar issue is in DrDump - https://drdump.com/Problem.aspx?ProblemID=215921

**Comment by sawilde** [comment] 2017-04-18 04:43
@diogonborges the issue is environmental and not a bug in OpenCover.

It seems you have two environment variables defined `PATH` and `Path` and unfortunately the .NET Framework does not handle that (thought it has been fixed in the corefx - https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/src/System/Diagnostics/ProcessStartInfo.cs#L75)

**Closed by sawilde** 2017-04-18 04:43 UTC
Labels: bug, doctor dump - crash report, medium
