### ISSUE TITLE
Using statement in .NET Core not 100% covered.

### ISSUE THREAD

**Issue by dlemstra** [OpenCover/opencover#704] opened 2017-04-22 10:15 UTC
### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [x] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016
- [x] AppVeyor (can also reproduce it locally)

### I have already...

- [x] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [x] have looked at the opencover output xml file in an attempt to resolve the issue.
- [x] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [x] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

The branch coverage should be 100%

### Actual Behavior

The branch coverage is 66.67% (https://github.com/dlemstra/opencover-bug/blob/master/Coverage.xml#L66)

### Steps to reproduce the problem:

I have created a very simple test project here: https://github.com/dlemstra/opencover-bug. You can build the project with the `build.cmd` file. This project is also build with AppVeyor: https://ci.appveyor.com/project/dlemstra/opencover-bug and then send to codecov (created by @stevepeak). There you can see that the using statement is only partially covered: https://codecov.io/gh/dlemstra/opencover-bug/src/443a17651538914b38ed96f49f86a716a39c1091/OpenCover/OpenCover.Tests/StreamExtensionsTests.cs

**Comment by sawilde** [comment] 2017-04-22 23:20
This is a duplicate of #675 

> This is the problem with branch coverage from the IL itself as the compiler may add extra branches for scenarios you haven't tested or are unable to.

**Closed by sawilde** 2017-04-22 23:20 UTC
Labels: low, support
