### ISSUE TITLE
Houston, we have a problem

### ISSUE THREAD

**Issue by ddur** [OpenCover/opencover#410] opened 2016-01-06 19:18 UTC
AppVeyor build at dogfood-release test, fails now and then at committing coverage report.
```
     [exec] Tests run: 444, Errors: 0, Failures: 0, Inconclusive: 0, Time: 28.4634269 seconds
     [exec]   Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
     [exec] 
     [exec] *MISSING COMMIT HERE*
     [exec] C:\projects\opencover\main\bin\release>OpenCover.Console.exe -register:user ....
```
Local build is OK.
```
     [exec] Tests run: 444, Errors: 0, Failures: 0, Inconclusive: 0, Time: 18,6052791625751 seconds
     [exec]   Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
     [exec]
     [exec] Committing...
     [exec] Visited Classes 89 of 98 (90.82)
     [exec] Visited Methods 406 of 469 (86.57)
     [exec] Visited Points 1931 of 2259 (85.48)
     [exec] Visited Branches 1109 of 1480 (74.93)
     [exec]
     [exec] ==== Alternative Results (includes all methods including those without corresponding source) ====
     [exec] Alternative Visited Classes 103 of 110 (93.64)
     [exec] Alternative Visited Methods 739 of 842 (87.77)
     [exec]
     [exec] E:\GitHub\opencover\main\bin\release>OpenCover.Console.exe -register:user ...
```

**Comment by ddur** [comment] 2016-01-06 19:33
Builds from 270 to 277 OK.
Then 278 fails but merge build 279 of same pull request is OK
Then to 281 OK.
Then 282 and 283 failed.

**Comment by ddur** [comment] 2016-01-07 03:20
Program.cs modified to show exception.
After some testing time, exception is finally here:
![opencover nocommit](https://cloud.githubusercontent.com/assets/3501612/12161368/36438d1c-b4f5-11e5-9b91-3ecb2862c3f5.png)

**Comment by ddur** [comment] 2016-01-07 03:33
Caught in Program.cs/CurrentDomainOnUnhandledException

**Comment by ddur** [comment] 2016-01-07 04:15
This is weird or I do not understand.

```switch (WaitHandle.WaitAny(processEvents))```
returns index of ```processEvents[index]``` that satisfied the wait 
https://msdn.microsoft.com/en-us/library/tdykks7z%28v=vs.110%29.aspx

1) Index can be any, above 2.
2) All indexes should be treated equal. ?

```
                while(block.Active)
                {
                    switch (WaitHandle.WaitAny(processEvents))
                    {
                        case 0:
                            _communicationManager.HandleCommunicationBlock(block.CommunicationBlock, b => { });
                            break;
                        case 1:
                            var data = _communicationManager.HandleMemoryBlock(block.MemoryBlock);
                            // don't let the queue get too big as using too much memory causes 
                            // problems i.e. the target process closes down but the host takes 
                            // ages to shutdown; this is a compromise. 
                            _messageQueue.Enqueue(data);
                            if (_messageQueue.Count > 400)
                            {
                                do
                                {
                                    ThreadHelper.YieldOrSleep(100);
                                } while (_messageQueue.Count > 200);
                            }
                            break;
                        case 2:
                            threadTerminated.Set();
                            return;
                    }
                }
```

**Comment by sawilde** [comment] 2016-01-07 07:40
I can only think the wait handle is being disposed, though the line number being reported doesn't make much sense.

**Comment by zabulus** [comment] 2016-01-07 07:57
The problem is about Event that was closed but there was some thread in ThreadPool, that was running lambda method. And this thread tries to reset already closed event. 
To fix this you need assure, that all threads finished and new won't be created before closing Event.

**Comment by zabulus** [comment] 2016-01-07 08:23
I think it is here:
https://github.com/OpenCover/opencover/blob/master/main/OpenCover.Framework/Manager/ProfilerManager.cs#L240

You're dispose events without assurance that thread is completed (```handle.Item2```). ```Task.WaitAll(tasks);``` is difficult to understand, I suppose it is timeout thread cancellation.

So what is happening:
1. You're running cancellation tasks in https://github.com/OpenCover/opencover/blob/master/main/OpenCover.Framework/Manager/ProfilerManager.cs#L233
2. It sets the ```terminateThread``` event (naming is not good, I suggest it ```cancelThreadEvent```)
3. ```ProcessBlock``` thread in this moment does some long work.
4. Then in https://github.com/OpenCover/opencover/blob/master/main/OpenCover.Framework/Manager/ProfilerManager.cs#L238 events disposed without waiting thread to finish (```threadTerminated``` also not good naming, ```threadFinished``` IMHO better).
5. After that https://github.com/OpenCover/opencover/blob/master/main/OpenCover.Framework/Manager/ProfilerManager.cs#L294 cycle tries to reset disposed events, and here is your exception.

Hope this would help.

**Comment by MaceWindu** [comment] 2016-01-07 08:29
Guys, I think you are looking at issue I already researched here:
https://github.com/OpenCover/opencover/issues/350#issuecomment-160657170

**Comment by sawilde** [comment] 2016-01-07 08:34
Do we need to dispose the handles? The app is terminating anyway and they will get freed then

**Comment by MaceWindu** [comment] 2016-01-07 08:49
Yeah, it feels terrible to not dispose them :)
Those are process handles to system named events, that will be closed on process shutdown, so I do not see any harm if we will allow system to close them. It will be simplest way to fix it, but at least we need a comment with description of why we do not dispose them.

**Comment by ddur** [comment] 2016-01-07 13:29
@sawilde 
>I can only think the wait handle is being disposed, though the line number being reported doesn't make much sense.

It is Release build, I was usually finding error somewhere below reported line within reported method.

**Comment by ddur** [comment] 2016-01-07 13:41
@MaceWindu 
>Guys, I think you are looking at issue I already researched here:
#350 (comment)

I had [OpenCover stucks in infinite loop](https://github.com/OpenCover/opencover/issues/373) once. 
It seemed to me that frequency of this failure was changing proportionally to test size and number of nontrivial .Where clauses in BasePersistance.cs.

**Comment by ddur** [comment] 2016-01-07 14:32
Looks like it takes now more time after tests ended, before "Committing..." message.
It would be nice to see some feedback like "Waiting..." or "Collecting data..."

**Comment by sawilde** [comment] 2016-01-07 15:06
Yeah I've noticed that, trying to determine why it's just started happening.

**Comment by sawilde** [comment] 2016-01-07 15:51
That should address the 20s(ish) hang on shutdown

**Comment by ddur** [comment] 2016-01-08 20:29
Here is again
https://ci.appveyor.com/project/sawilde/opencover/build/4.6.311
```
     [exec] .......................
     [exec] Tests run: 475, Errors: 0, Failures: 0, Inconclusive: 0, Time: 38.3882852 seconds
     [exec]   Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
     [exec] 
     [exec] CurrentDomainOnUnhandledException
     [exec] An exception occured: Safe handle has been closed
     [exec] stack:    at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
     [exec]    at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
     [exec]    at Microsoft.Win32.Win32Native.ResetEvent(SafeWaitHandle handle)
     [exec]    at System.Threading.EventWaitHandle.Reset()
     [exec]    at OpenCover.Framework.Manager.ProfilerManager.<>c__DisplayClass31.<ProcessBlock>b__2f(Object state) in c:\projects\opencover\main\OpenCover.Framework\Manager\ProfilerManager.cs:line 307
     [exec]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     [exec]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     [exec]    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
     [exec]    at System.Threading.ThreadPoolWorkQueue.Dispatch()
     [exec] 
```

**Comment by ddur** [comment] 2016-01-08 20:41
And again
https://ci.appveyor.com/project/sawilde/opencover/build/4.6.312

**Comment by ddur** [comment] 2016-01-08 21:31
@sawilde 
Question about loop and case 2: return. 
As far as I understand here, when ```case 2: return;``` then  ```while (block.Active)``` is true and ```_memoryManager.RemoveDeactivatedBlocks();``` is never invoked. 
Maybe ```case 2:``` should be simply removed?
```
        private WaitCallback ProcessBlock(ManagedBufferBlock block,
            EventWaitHandle threadActivatedEvent, ThreadTermination threadTermination)
        {
            return state =>
            {
                var processEvents = new WaitHandle[]
                {
                    block.CommunicationBlock.ProfilerRequestsInformation,
                    block.MemoryBlock.ProfilerHasResults,
                    threadTermination.CancelThreadEvent
                };
                threadActivatedEvent.Set();

                try
                {
                    while (block.Active)
                    {
                        switch (WaitHandle.WaitAny(processEvents))
                        {
                            case 0:
                                _communicationManager.HandleCommunicationBlock(block.CommunicationBlock, b => { });
                                break;
                            case 1:
                                var data = _communicationManager.HandleMemoryBlock(block.MemoryBlock);
                                // don't let the queue get too big as using too much memory causes 
                                // problems i.e. the target process closes down but the host takes 
                                // ages to shutdown; this is a compromise. 
                                _messageQueue.Enqueue(data);
                                if (_messageQueue.Count > 400)
                                {
                                    do
                                    {
                                        ThreadHelper.YieldOrSleep(100);
                                    } while (_messageQueue.Count > 200);
                                }
                                break;
                            case 2:
                                return;
                        }
                    }
                    _memoryManager.RemoveDeactivatedBlocks();
                }
                finally
                {
                    threadTermination.ThreadFinishedEvent.Set();    
                }
            };
```

**Comment by ddur** [comment] 2016-01-09 14:50
Excellent! We have that exception reporting again.
https://ci.appveyor.com/project/sawilde/opencover/build/4.6.313

Looks like my changes indeed influence frequency of this exception.
I added resource hungry test (File IO).

**Comment by sawilde** [comment] 2016-01-09 14:53
> Maybe case 2: should be simply removed?

when `case 2:` the host is closing everything down so there is no need to `RemoveDeactivatedBlocks` as they are all going anyway.

**Comment by ddur** [comment] 2016-01-09 15:11
maybe then 
```
                            case 0:
                                _communicationManager.HandleCommunicationBlock(block.CommunicationBlock, b => { });
                                break;
```
requires some delay as case 1?
After all, exception is reported exact at that line.

**Comment by sawilde** [comment] 2016-01-09 15:21
The line number is incorrect the issues seems to be with wait handles so I can only assume it is trying to wait on a handle that has been killed

**Comment by ddur** [comment] 2016-01-09 19:52
Ok. Let's try further.
In whole OpenCover there are only 3 ```System.Threading.EventWaitHandle.Reset()```
I guess, the first one in picture below is problem.
This Exception is thrown if ```.Reset``` is called twice.
It can be only Profiler that called ```.Reset```.
If profiler has timeout and reset analogue to ```SendChunkAndWaitForConfirmation```?
```
    WaitHandle.SignalAndWait(mcb.InformationReadyForProfiler, mcb.InformationReadByProfiler, 10000, false);
    mcb.InformationReadByProfiler.Reset();
```
And if  ```_communicationManager.HandleCommunicationBlock``` does not respond within profiler timeout, exception must be thrown.
?

![issue410](https://cloud.githubusercontent.com/assets/3501612/12217981/67adc44e-b711-11e5-88d8-efbc79940159.png)

**Comment by ddur** [comment] 2016-01-09 21:36
Exception is still present
https://ci.appveyor.com/project/sawilde/opencover/build/4.6.319

**Comment by sawilde** [comment] 2016-01-10 00:41
> https://ci.appveyor.com/project/sawilde/opencover/build/4.6.320

I see we have a much better stack trace than 313 and that makes more sense (I can only assume inlining took place.

The `Reset` isn't the same as a `Close` but as far as I can recall only the host should be closing/disposing the events. 

It only seems to be happening during shutdown so I am considering (last resort) just consuming the error so it does not kill the whole process.

I sometimes wish I hadn't tried to improve the performance around handling multiple 'processes' at the same time.

**Comment by sawilde** [comment] 2016-01-10 00:59
I am thinking of adding an .ini (yes one of those) to stop the runtime inlining whilst we investigate this issue.

http://www.hanselman.com/blog/ReleaseISNOTDebug64bitOptimizationsAndCMethodInliningInReleaseBuildCallStacks.aspx

**Comment by ddur** [comment] 2016-01-10 01:06
@sawilde 
Just found out that is not problem in first reset!
```
        private static void SendChunkAndWaitForConfirmation(int writeSize, IManagedCommunicationBlock mcb)
        {
            mcb.StreamAccessorComms.Seek(0, SeekOrigin.Begin);
            mcb.StreamAccessorComms.Write(mcb.DataCommunication, 0, writeSize);
            mcb.StreamAccessorComms.Flush();

            WaitHandle.SignalAndWait(mcb.InformationReadyForProfiler, mcb.InformationReadByProfiler, 10000, false);
-----------------------------------------------------------------
            mcb.InformationReadByProfiler.Reset();
-----------------------------------------------------------------
        }
```
This reset is throwing exception. I'm not sure why is it here.

**Comment by molnargab** [comment] 2016-01-10 01:07
By the way, do we need a `ManualResetEvent` here? We reset it as soon as it's set by the profiler, somewhat similar to what an `AutoResetEvent` does.

Also do we need to reset the event in case of a timeout?  We don't know if the profiler read it or not.
It is also possible that the host times out, resets the event, and after that the profiler sets it once finished.

**Comment by ddur** [comment] 2016-01-10 01:08
I caught that exception and there is not change in coverage percentage.
As far as can tell, nothing is lost

**Comment by sawilde** [comment] 2016-01-10 01:15
> This reset is throwing exception. I'm not sure why is it here.

Yes I am looking at the same line - I think what has happened is 
1) the profiler has gone (not responding) 
2) the host has attempted to stop and timedout
3) the buffer gets cleaned up
4) the SignalAndWait returns and *poof*

**Comment by ddur** [comment] 2016-01-10 01:16
```
     [exec] Completed Tests...
     [exec] .......................
     [exec] Tests run: 483, Errors: 0, Failures: 0, Inconclusive: 0, Time: 25,9198987580824 seconds
     [exec]   Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0
     [exec]
     [exec] HandleCommunicationBlock
     [exec] An exception occured: Safe handle has been closed
     [exec] stack:    at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
     [exec]    at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
     [exec]    at Microsoft.Win32.Win32Native.ResetEvent(SafeWaitHandle handle)
     [exec]    at System.Threading.EventWaitHandle.Reset()
     [exec]    at OpenCover.Framework.Communication.CommunicationManager.SendChunkAndWaitForConfirmation(Int32 writeSize, IManagedCommunicationBlock mcb) in e:\GitHub\opencover\main\OpenCover.Framework\Communication\CommunicationManager.cs:line 82
     [exec]    at OpenCover.Framework.Communication.CommunicationManager.HandleCommunicationBlock(IManagedCommunicationBlock mcb, Action`1 offloadHandling) in e:\GitHub\opencover\main\OpenCover.Framework\Communication\CommunicationManager.cs:line 64
     [exec] Committing...
     [exec] Visited Classes 89 of 94 (94.68)
     [exec] Visited Methods 430 of 442 (97.29)
     [exec] Visited Points 2039 of 2168 (94.05)
     [exec] Visited Branches 1083 of 1285 (84.28)
     [exec]
     [exec] ==== Alternative Results (includes all methods including those without corresponding source) ====
     [exec] Alternative Visited Classes 103 of 106 (97.17)
     [exec] Alternative Visited Methods 769 of 814 (94.47)
     [exec]
 ```

**Comment by sawilde** [comment] 2016-01-10 01:18
> By the way, do we need a ManualResetEvent here? 

I did try with AutoResetEvent but didn't behave the way I expected at the time (of course the code has changed a bit since then)

**Comment by sawilde** [comment] 2016-01-10 01:23
What's annoying is I can't repeat it

**Comment by ddur** [comment] 2016-01-10 01:24
I ran 3 consoles in parallel.

**Comment by sawilde** [comment] 2016-01-10 01:26
> I ran 3 consoles in parallel. :D 

I'll give it a go

**Comment by ddur** [comment] 2016-01-10 01:29
Only dogfood-release, you will have it within 15 minutes. 
If not, try slower PC

**Comment by sawilde** [comment] 2016-01-10 01:31
> If not, try slower PC

I only have the one (my work one is more poweful but I don't develop OpenSource on that one) and it's only 1.7GHz

**Comment by ddur** [comment] 2016-01-10 01:44
Then, maybe you need faster one :)
My is 4 years old AMD 2.7GHz, recently extended to 10G RAM, and Win10/64 on 128G SSD

**Comment by sawilde** [comment] 2016-01-10 01:57
> Then, maybe you need faster one :)

I know...

**Comment by MaceWindu** [comment] 2016-01-10 11:25
I'm sorry, it looks like my comment wasn't clear enough, so I will rephrase it in less words:

OpenCover throws this exception from multi-threaded processes due to race conditions:
1. each block processed by separate process
2. each process tries to remove ALL deactivated blocks after block processing
Now is the race condition:
1. thread1 one starts processing of block1
2. block1 became inactive
3. thread2 finished its work on block2 and called RemoveDeactivatedBlocks and disposed all inactive blocks (block1 and block2 and maybe more)
4. thread1 finished its block processing and decided to reset block event - BANG, it is already disposed and cannot be reset.

As you can see, my proposal was to change cleanup logic for threads to cleanup only their own block.

**Comment by sawilde** [comment] 2016-01-10 11:43
@MaceWindu I see the merit in what you say - we can definitely try that

**Comment by sawilde** [comment] 2016-01-11 13:56
Well it definitely looks more stable especially on the build box...

**Comment by ddur** [comment] 2016-01-11 18:57
Exception is caught, will not be thrown before commit.
XML report will be always committed.
I think we can close this issue.

**Comment by sawilde** [comment] 2016-01-12 07:40
I agree

**Closed by sawilde** 2016-01-12 07:40 UTC
Labels: bug, high
