### ISSUE TITLE
Regression in async/await coverage in 4.7.922

### ISSUE THREAD

**Issue by sharwell** [OpenCover/opencover#881] opened 2019-03-09 21:35 UTC
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [ ] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET 4.7
- [ ] .NET 4.7.1
- [x] .NET 4.7.2
- [ ] .NET Core 1.0.0
- [ ] .NET Core 2.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [ ] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

`await` statements are marked as covered when using 4.7.922 with portable PDB.

### Actual Behavior

`await` statements are marked as _partially_ covered when using 4.7.922 with portable PDB.

### Steps to reproduce the problem:

The problem can be seen in https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/2913.

- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [ ] sample code or link to repository/gist is available (support is much faster this way)

**Comment by sawilde** [comment] 2019-03-10 21:18
@sharwell thanks for report

We haven't changed the way we instrument it so the answer may lie in what the PDB produced has indicated as sequence points.

**Comment by MonkAlex** [comment] 2019-03-12 16:31
Has the [same result](https://codecov.io/gh/MonkAlex/MangaReader/pull/132/src/Tests/Tests.Entities/Manga/MangachanStructure.cs?before=Tests/Tests.Entities/Manga/MangachanStructure.cs) in .NET 4.6.1

**Comment by sawilde** [comment] 2019-04-22 05:18
@sharwell They are marked as partially covered I think due to a branch that exists that is not being exercised

![image](https://user-images.githubusercontent.com/297165/56483963-7b0f6780-6510-11e9-8b1a-db915f4f6834.png)

```
<Method visited="true" cyclomaticComplexity="3" nPathComplexity="2" sequenceCoverage="100" branchCoverage="66.67" crapScore="3" isConstructor="false" isStatic="false" isGetter="false" isSetter="false">
              <Summary numSequencePoints="4" visitedSequencePoints="4" numBranchPoints="3" visitedBranchPoints="2" sequenceCoverage="100" branchCoverage="66.67" maxCyclomaticComplexity="3" minCyclomaticComplexity="3" maxCrapScore="3" minCrapScore="3" visitedClasses="0" numClasses="0" visitedMethods="1" numMethods="1" />
              <MetadataToken>100663300</MetadataToken>
              <Name>System.Void Sample.Target.AsyncAwait/&lt;Execute&gt;d__0::MoveNext()</Name>
              <FileRef uid="499" />
              <SequencePoints>
                <SequencePoint vc="1" uspid="11383" ordinal="0" offset="14" sl="13" sc="9" el="13" ec="10" bec="0" bev="0" fileid="499" />
                <SequencePoint vc="1" uspid="11384" ordinal="1" offset="15" sl="14" sc="13" el="14" ec="43" bec="0" bev="0" fileid="499" />
                <SequencePoint vc="1" uspid="11385" ordinal="2" offset="26" sl="15" sc="13" el="15" ec="72" bec="2" bev="1" fileid="499" />
                <SequencePoint vc="1" uspid="11386" ordinal="3" offset="179" sl="16" sc="9" el="16" ec="10" bec="0" bev="0" fileid="499" />
              </SequencePoints>
              <BranchPoints>
                <BranchPoint vc="1" uspid="11387" ordinal="0" offset="55" sl="15" path="0" offsetend="57" fileid="499" />
                <BranchPoint vc="0" uspid="11388" ordinal="1" offset="55" sl="15" path="1" offsetend="121" fileid="499" />
              </BranchPoints>
              <MethodPoint vc="2" uspid="11389" ordinal="0" offset="0" />
            </Method>
```

Looking at the IL it looks like a test against `IsCompleted` 

```
        IL_002f: stloc.1      // V_1

        IL_0030: ldloca.s     V_1
        IL_0032: call         instance bool valuetype [mscorlib]System.Runtime.CompilerServices.TaskAwaiter`1<class [System.Net.Http]System.Net.Http.HttpResponseMessage>::get_IsCompleted()
        IL_0037: brtrue.s     IL_0079
        IL_0039: ldarg.0      // this
        IL_003a: ldc.i4.0
```

Not sure what I should do other than tell you to ignore them - we have in the past tried to ignore sequences but it was never a battle we could win as the IL output kept changing based on the .NET release.

I'll see if this is what you are seeing and if it is then I am at a loss at the moment on how to proceed.

**Comment by sawilde** [comment] 2019-04-22 09:23
@sharwell I pulled the latest stylecop analyzer code and ran 4.7.922 of `OpenCover ` against it and I got coverage of the `await`s, again the only partial coverage was due to the branches as mentioned before.
![image](https://user-images.githubusercontent.com/297165/56493870-d737b300-6533-11e9-872a-2ac567eff3c4.png)
I do note that when you used 4.7.922 you are still converting the PDBs (due to #800) which there is no need to do anymore as the latest `OpenCover` handles those PDB formats as mentioned in the comments.

Let me know if I am not following your issue correctly.

**Comment by sawilde** [comment] 2019-04-23 07:38
@sharwell @MonkAlex I decided to have a review about how we go about ignoring compiler generated branches - I think I may have a solution that is more reliable than the old way we did it. I am still a little nervous that I may end up hiding branches that shouldn't be hidden.

The referenced build should produce a package that may solve your issues. If you have a chance to check that would be great.

**Comment by sharwell** [comment] 2019-06-05 14:37
@sawilde Is there an easy way I can reference that build (e.g. NuGet or MyGet)?

**Comment by sawilde** [comment] 2019-06-14 05:06
@sharwell I do push to myget 

https://www.myget.org/feed/opencover/package/nuget/OpenCover

**Comment by MonkAlex** [comment] 2019-06-16 20:43
4.7.945-rc lost my core project in coverage, i change only opencover version.
From 4.6.519:
https://codecov.io/gh/MonkAlex/MangaReader/tree/b4ae1717055e87c53bbcc2167298f3cc952c57e1
From 4.7.945-rc:
https://codecov.io/gh/MonkAlex/MangaReader/tree/02b55ef0509eb75d45a20a5e5ff73d430abf9380

**Comment by sawilde** [comment] 2019-06-17 00:49
@MonkAlex please create a new issue to explain your issue in detail

**Comment by sharwell** [comment] 2019-06-17 15:48
@sawilde Thank you for the update. An unrelated infrastructure problem is currently impacting my ability to test this, but I'll let you know as soon as I get it tested.

Thanks!

**Comment by airbreather** [comment] 2019-07-19 14:49
> I am still a little nervous that I may end up hiding branches that shouldn't be hidden.

My 2 cents... I'm not **perfectly** comfortable flat-out ignoring the compiler-generated `IsCompleted` branches, since it's possible that a user's async method may only be correct in cases where a particular `await` instruction executes synchronously (or vice-versa).

First thing that comes to mind is if someone slaps `.ConfigureAwait(false)` somewhere that they shouldn't have: if no test ever sees it yield, then it never leaves the original sync context, so there's actually a visible difference.  Of course, **merely** knowing that both sides of the branch are covered isn't enough to guarantee that you would be able to identify a misplaced `.ConfigureAwait(false)`, but coverage isn't a perfect metric in general, anyway...

Perhaps the **100% ideal** behavior would be to ignore the "executed synchronously or not?" branches when reporting traditional branch coverage info, **but** to also dump them into a separate bucket that reports, for each `await`, whether or not both synchronous and asynchronous paths were observed.

That said, I don't think I've ever encountered a situation where I would benefit from knowing this information, so I wouldn't mind OpenCover just ignoring the branches and leaving it at that.

**Comment by sawilde** [comment] 2019-07-19 23:11
I am of a similar mind, the coverage of branches is supposed to help the person writing tests identify if code is missing the appropriate tests for their code. The branches in generated code often cause confusion is it is hard for people to understand the coverage report (especially branches) when the compiler creates all this extra code and has branches that they feel a need to exercise/test because of some 100% coverage mandate (I hate testing for coverage sake BTW as it often leads to awful tests)

**Comment by sharwell** [comment] 2019-11-08 15:06
@sawilde I finally set up a new controlled experiment for 4.7.945-rc. You can see the full set of changes in this pull request:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/3062

I used Windows PDBs for both the baseline and the PR builds. For some reason, 4..7.945-rc is including coverage for the test assemblies, but has omitted all coverage information for two production assemblies. This sounds like what https://github.com/OpenCover/opencover/issues/881#issuecomment-502484374 is describing.

**Comment by sawilde** [comment] 2019-11-12 02:12
@sharwell thanks

**Comment by sharwell** [comment] 2019-11-12 14:48
Let me know if you want me to try another build 😄

**Comment by costin-zaharia-sonarsource** [comment] 2020-03-19 14:16
Hi,

We are also having this issue analyzing [sonar-dotnet](https://github.com/SonarSource/sonar-dotnet).

Results with `4.7.922`:

![image](https://user-images.githubusercontent.com/56015273/77076442-244a3080-69f4-11ea-85b5-31c02663c131.png)

Results with `4.6.519.0`:
![image](https://user-images.githubusercontent.com/56015273/77076684-71c69d80-69f4-11ea-9c01-08a4e7576b29.png)

**Comment by sawilde** [comment] 2020-03-24 23:30
@costin-zaharia-sonarsource we have tried to hide some autogenerated methods/branches (as it was causing more issues than it resolved) in the last release hence why your line coverage stays the same but the conditional coverage has reduced.

**Comment by silvafabiano** [comment] 2020-04-10 00:36
1. **Version 4.7.922**
![image](https://user-images.githubusercontent.com/4886419/78951703-6a515c00-7aa9-11ea-9b2b-cf38070edbf5.png)


2. **Version 4.7.995-rc**
![image](https://user-images.githubusercontent.com/4886419/78951762-9f5dae80-7aa9-11ea-8fe3-b5e3573df343.png)

@sawilde can I use this version in my continuous integration production environment or do we expect an official version?

**Comment by sawilde** [comment] 2020-05-22 04:31
feel free to use it - I don't know when I am going to get back to OpenCover to address issues or make new releases

**Comment by lionelschiepers** [comment] 2020-11-16 14:04
Hi,

Could we expect a new release that adresses this await/async regression soon?

Thanks for this great project :-)

**Comment by sawilde** [comment] 2020-11-23 07:33
my plan is to do a new release around xmas

**Comment by sawilde** [comment] 2021-01-10 21:44
release candidate 4.7.1137-rc

**Closed by sawilde** 2021-01-10 21:44 UTC
Labels: medium, support
