### ISSUE TITLE
OpenCover does not report on some of the modules

### ISSUE THREAD

**Issue by MarkKharitonov** [OpenCover/opencover#900] opened 2019-06-11 19:48 UTC
### My Framework

- [X] .NET 4.7.2

### My Environment

- [X] Windows 10

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [X] repeated the problem using the latest release of OpenCover published on NuGet.org
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [X] have looked at the opencover output xml file in an attempt to resolve the issue.
- [X] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded

### Expected Behavior

Some coverage produced.

### Actual Behavior

No coverage produced.

### Steps to reproduce the problem:

- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf) again because we know you probably didn't do it the first time.
- [X] sample code or link to repository/gist is available (support is much faster this way) 

I describe the issue in detail in this SO question - https://stackoverflow.com/questions/56549870/why-does-opencover-not-find-all-the-modules-when-running-code-through-nunit
Another related question - https://stackoverflow.com/questions/56552781/how-to-limit-the-covered-code-as-reported-by-opencover-correctly

**Comment by sawilde** [comment] 2019-06-14 05:19
@MarkKharitonov Unfortunately I don't see the issue myself and can't replicate your scenario.

I'd remove the switches `-hideskipped:MissingPdb` and `-mergeoutput` as you want a clean run each time until you have got the coverage tool working.

**Comment by MarkKharitonov** [comment] 2019-06-14 13:11
I updated the post - ran without any `-merge...` or `-hideskipped...` flags. Same result.
What should I do next? Is there any way to troubleshoot it?

**Comment by sawilde** [comment] 2019-06-19 23:57
@MarkKharitonov - you can run DebugView (sysinternals) to get more info on what is happening and you can adjust the logging level `-log:All`

> Does OpenCover has commercial support?
No

**Comment by MarkKharitonov** [comment] 2019-06-21 17:16
I have just rerun it with the DebugView and log level of All. Cannot say that All produced that much of log output. Anyway, attaching the relevant files.

[InternalTrace.23900.log](https://github.com/OpenCover/opencover/files/3315450/InternalTrace.23900.log)
[InternalTrace.23900.UnitTests.dll.log](https://github.com/OpenCover/opencover/files/3315451/InternalTrace.23900.UnitTests.dll.log)
[OpenCover.DebugView.log](https://github.com/OpenCover/opencover/files/3315452/OpenCover.DebugView.log)

**Comment by sawilde** [comment] 2019-06-24 01:53
```
00000088	29.58092499	[23900] OpenCover: (Profiler) ::JITCompilationStarted(EE5A6698, ...) => 100666238, EE5A4488 => C:\Xyz\tip\Test\UnitTests\bin\Debug\nunit.framework.dll	
00000141	203.45942688	[23900] OpenCover: (Profiler) ProfilerCommunication::RequestInformation(...) => Communication (Chat channel - TrackAssembly) with host has failed (0x102, 60000)	
```
Is the assembly being loaded very large? It could be timing out...

**Comment by MarkKharitonov** [comment] 2019-06-27 19:19
How can we know the name of the assembly that causes the timeout?

**Comment by MarkKharitonov** [comment] 2019-06-28 13:45
Hi, here are the lengths of the dlls:
```
-a----        6/27/2019  11:47 AM         818176 AccrualEngine.dll                                                                                                                                       
-a----        6/27/2019  11:45 AM         319488 AdminService.dll                                                                                                                                        
-a----        6/27/2019  11:47 AM         691200 BenefitsCalculationEngine.dll                                                                                                                           
-a----        6/27/2019  11:46 AM        1764864 DataProcessor.dll                                                                                                                                       
-a----        6/27/2019  11:47 AM       15333888 DataSvc.dll                                                                                                                                             
-a----        6/27/2019  11:47 AM        1356288 DeviceServices.dll                                                                                                                                      
-a----        6/27/2019  11:47 AM        4753920 ExportFramework.dll                                                                                                                                     
-a----        6/27/2019  11:47 AM         460288 Forecaster.dll                                                                                                                                          
-a----        6/27/2019  11:47 AM         151552 HRMappingRuleEngine.dll                                                                                                                                 
-a----        6/27/2019  11:47 AM          96256 KpiCalculationEngineServer.dll                                                                                                                          
-a----        6/27/2019  11:46 AM         204288 LaborDeploymentEngineServer.dll                                                                                                                         
-a----        6/27/2019  11:47 AM          14336 MultiApprovalProcessor.dll                                                                                                                              
-a----        6/27/2019  11:47 AM         369152 PunchStatusReconciliationEngine.dll                                                                                                                     
-a----        6/27/2019  11:47 AM         124928 RateEngine2.dll                                                                                                                                         
-a----        6/27/2019  11:47 AM         171008 RateEngineDataProviderServer.dll                                                                                                                        
-a----        6/21/2019   7:28 PM          40448 ReportingEngine.dll                                                                                                                                     
-a----        6/27/2019  11:47 AM       17964032 ReportingEngineSupport.dll                                                                                                                              
-a----        6/27/2019  11:45 AM        9668096 Resources.dll                                                                                                                                         
-a----        2/14/2019   1:41 PM         169984 RestSharp.dll                                                                                                                                           
-a----        6/27/2019  11:47 AM        5176832 RuleEngine.dll                                                                                                                                          
-a----        6/27/2019  11:47 AM        2861568 RuleEngineDataProvider.dll                                                                                                                              
-a----        6/27/2019  11:47 AM         129536 RuleEngineHelper.dll                                                                                                                                    
-a----        6/27/2019  11:47 AM         581120 SchedulePolicyValidation.dll                                                                                                                            
-a----        6/27/2019  11:47 AM         136704 SchedulerEngines.dll                                                                                                                                    
-a----        6/27/2019  11:47 AM         631296 ScheduleSolver.dll                                                                                                                                      
-a----        6/27/2019  11:47 AM         172032 StaffAssignment.dll                                                                                                                                     
-a----        6/27/2019  11:47 AM         549376 TransmissionSvc.dll                                                                                                                                     
-a----        6/27/2019  11:47 AM        3962880 UnitTests.dll                                                                                                                                           
-a----        6/21/2019   7:24 PM           5120 Versioning.dll                                                                                                                                        
-a----        6/27/2019  11:47 AM         253440 WorkFlowFormRuleEngine.dll                                                                                                                              
-a----        6/27/2019  11:45 AM          43520 WorkTimeCalculationEngine.dll                                                                                                                           
-a----        6/27/2019  11:45 AM          39424 Xyz.AdminServiceProxy.dll                                                                                                                          
-a----        6/27/2019  11:47 AM          84992 Xyz.BusinessAPI.Core.dll                                                                                                                           
-a----        6/27/2019  11:47 AM       18375680 Xyz.BusinessAPI.dll                                                                                                                                
-a----        6/27/2019  11:45 AM         866304 Xyz.Common.dll                                                                                                                                     
-a----        6/27/2019  11:45 AM       13087744 Xyz.Data.dll                                                                                                                                       
-a----        6/27/2019  11:45 AM         178688 Xyz.DataManager.dll                                                                                                                                
-a----        6/27/2019  11:45 AM          29184 Xyz.XyzIdentity.Client.dll                                                                                                                    
-a----        6/27/2019  11:46 AM         137216 Xyz.HtmlPlatform.dll                                                                                                                               
-a----        6/27/2019  11:45 AM          71680 Xyz.PDFReportGenerator.dll                                                                                                                         
-a----        6/27/2019  11:47 AM         111616 Xyz.WFM.Core.WorkContractPremium.Engine.dll                                                                                                        
-a----        6/27/2019  11:47 AM          44544 Xyz.WFM.Time.dll                                                                                                                                   
-a----        6/27/2019  11:45 AM         548864 Xyz.Common.Security.MemberSession.dll                                                                                                              
-a----        6/27/2019  11:47 AM       30384128 Xyz.DB.DL.dll                                                                                                                                      
```
These are the dlls found in the bin directory. How can we deal with the timeout? What is next?

**Comment by sawilde** [comment] 2019-07-01 00:08
There are a number of switches that help these can be seen by running OpenCover and viewing them

https://github.com/OpenCover/opencover/wiki/Usage or the PDF can help with more details 

Adding filters also helps i.e. if you know if you have a lot of code that you do not wish to cover.

**Comment by MarkKharitonov** [comment] 2019-07-01 02:06
Well, here you come to complete a circle. I have started with filters, then removed all of them, then what - add them back?
Is there a way to capture more information? A debug build, maybe? Anything?

**Comment by kevinbosman** [comment] 2019-10-21 20:15
This sounds like it is related to #728. The 60s timeout is sometimes too short.

**Comment by MarkKharitonov** [comment] 2019-10-22 02:32
Yup, you are right by the looks of it.

**Comment by sawilde** [comment] 2021-01-02 02:43
closing as duplicate of #728

**Closed by sawilde** 2021-01-02 02:43 UTC
Labels: feature, medium
